const steps=[
  ['z = W<sub>enc</sub> s','Encode what light transport needs','A non-negative linear encoder compresses each spectrum to six channels. Linearity preserves scaling and addition exactly; training makes channel-wise multiplication approximate the corresponding spectral operation.'],
  ['[z₁ z₂ z₃]  /  [z₄ z₅ z₆]','Let the RGB renderer process the code','The six latent channels are split into two RGB triplets. Existing shading and light-transport operations process these triplets in two ordinary passes, without changes inside the renderer.'],
  ['ŝ = W<sub>dec</sub> z','Recover spectral information','A well-trained linear decoder merges the six rendering channels and decodes them, before converting them for colour display. Lightweight upsamplers can bring legacy RGB assets into the same latent space.']
];
const tabs=[...document.querySelectorAll('[data-step]')];
function selectStep(i){tabs.forEach((button,j)=>{button.setAttribute('aria-selected',j===i);button.tabIndex=j===i?0:-1});document.querySelector('#formula').innerHTML=steps[i][0];document.querySelector('#step-title').textContent=steps[i][1];document.querySelector('#step-copy').textContent=steps[i][2];document.querySelector('#step-panel').setAttribute('aria-labelledby',`step-${i}`)}
tabs.forEach((button,i)=>{button.addEventListener('click',()=>selectStep(i));button.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(i+1)%tabs.length;if(event.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();selectStep(next);tabs[next].focus()}})});

const materials=[
  {key:'glass-og550',title:'Coloured glass',detail:'OG550 · surface transmittance',metric:'Mean ΔE₂₀₀₀: 1.28 codec / 10.52 RGB',description:'A sharp spectral cutoff in Schott glass is difficult to preserve after an early RGB collapse.'},
  {key:'gold',format:'png',title:'Gold conductor',detail:'Measured metal · D65',metric:'Mean ΔE₂₀₀₀: 0.65 codec / 8.98 RGB',description:'The spectral Fresnel response preserves the hue and intensity of metallic reflection.'},
  {key:'sss-wine',title:'Subsurface scattering',detail:'Wine · homogeneous medium',metric:'Mean ΔE₂₀₀₀: 2.19 codec / 14.39 RGB',description:'Absorption and scattering travel through the renderer as encoded per-channel volume parameters.'},
  {key:'sss-hand',format:'png',title:'Heterogeneous volume',detail:'Per-voxel spectral hand',metric:'Mean ΔE₂₀₀₀: 0.93 codec / 4.00 RGB',description:'Spatially varying skin features, including freckles, knuckles and veins, remain distinguishable.'}
];
const narrowband=[
  {key:'narrowband-425',format:'png',title:'425 nm',detail:'BLUE CELL · FWHM 40 NM',metric:'Mean / p95 ΔE₂₀₀₀ — ours: 1.50 / 3.37 · RGB: 23.78 / 52.31',description:'Gaussian narrowband illumination centred at 425 nm.',spd:'narrowband-425-spd.png'},
  {key:'narrowband-525',format:'png',title:'525 nm',detail:'GREEN CELL · FWHM 40 NM',metric:'Mean / p95 ΔE₂₀₀₀ — ours: 1.17 / 3.04 · RGB: 12.48 / 35.48',description:'Gaussian narrowband illumination centred at 525 nm.',spd:'narrowband-525-spd.png'},
  {key:'narrowband-625',format:'png',title:'625 nm',detail:'RED CELL · FWHM 40 NM',metric:'Mean / p95 ΔE₂₀₀₀ — ours: 1.08 / 2.42 · RGB: 21.68 / 44.24',description:'Gaussian narrowband illumination centred at 625 nm.',spd:'narrowband-625-spd.png'}
];
const engines=[
  {key:'blender',title:'Blender Cycles',detail:'Broadband coloured lights',description:'Open-source path tracing under broadband illumination.'},
  {key:'keyshot',title:'KeyShot',detail:'Environment-map lighting',description:'Product visualisation under a spectral environment map.'},
  {key:'maya',title:'Maya Arnold',detail:'Structured light · light 2',description:'Offline production rendering with spectrally structured illumination.'},
  {key:'unreal',title:'Unreal Engine 5',detail:'Lumen · lighting 1',description:'A real-time pipeline with Lumen global illumination.'}
];
const labels={rgb:'RGB baseline',gt:'Spectral reference',codec:'Codec · spectral assets',ours:'Full RGB-asset route',latent:'Our codec',spectral_gt:'Spectral reference'};
function comparisonCard(item,type){const engine=type==='engine';const narrow=type==='narrowband';const startLeft=engine?'codec':'latent';const format=item.format||'webp';const leftChoices=engine?[['codec',labels.codec],['ours',labels.ours]]:[];const rightChoices=[['rgb',labels.rgb],['gt',labels.gt]];const cardType=engine?'RENDERER':narrow?'NARROWBAND':'MATERIAL';return `<article class="comparison-card" data-key="${item.key}" data-format="${format}"><div class="card-top"><div><span class="eyebrow">${item.detail}</span><h3>${item.title}</h3></div><span class="card-index">${cardType}</span></div><p>${item.description}</p>${item.spd?`<figure class="narrowband-spd"><figcaption><span class="eyebrow">ILLUMINATION SPD</span><span>Gaussian spectrum · FWHM 40 nm</span></figcaption><a href="assets/${item.spd}" target="_blank" rel="noopener"><img src="assets/${item.spd}" alt="${item.title} narrowband illumination spectrum" loading="lazy"></a></figure>`:''}${engine?`<div class="card-controls"><span>Show</span><div class="segmented" role="group" aria-label="${item.title} method">${leftChoices.map(([value,label],i)=>`<button type="button" data-side="left" data-value="${value}" aria-pressed="${i===0}">${label}</button>`).join('')}</div></div>`:''}<div class="card-controls"><span>Compare with</span><div class="segmented" role="group" aria-label="${item.title} comparison">${rightChoices.map(([value,label],i)=>`<button type="button" data-side="right" data-value="${value}" aria-pressed="${i===0}">${label}</button>`).join('')}</div></div><div class="comparison mini-comparison" style="--split:50%"><img class="compare-base" src="assets/${item.key}-rgb.${format}" alt="${item.title}: RGB baseline" loading="lazy"><img class="overlay compare-overlay" src="assets/${item.key}-${startLeft}.${format}" alt="${item.title}: ${labels[startLeft]}" loading="lazy"><div class="divider"><span>↔</span></div><span class="image-label left compare-left-label">${labels[startLeft]}</span><span class="image-label right compare-right-label">RGB baseline</span><input type="range" min="0" max="100" value="50" aria-label="Move the divider in the ${item.title} comparison"></div>${item.metric?`<p class="card-metric">${item.metric}</p>`:''}</article>`}
document.querySelector('#material-gallery').innerHTML=materials.map(item=>comparisonCard(item,'material')).join('');
document.querySelector('#narrowband-gallery').innerHTML=narrowband.map(item=>comparisonCard(item,'narrowband')).join('');
document.querySelector('#engine-gallery').innerHTML=engines.map(item=>comparisonCard(item,'engine')).join('');
const enginePresentation={
  blender:{ratio:'1 / 1',caption:'Broadband light spectra'},
  maya:{ratio:'16 / 9',caption:'Structured light spectrum'},
  keyshot:{ratio:'4 / 3',caption:'Environment illumination'},
  unreal:{ratio:'16 / 9',caption:'Scene light spectra'}
};
document.querySelectorAll('#engine-gallery .comparison-card').forEach(card=>{
  const {ratio,caption}=enginePresentation[card.dataset.key];
  card.querySelector('.mini-comparison').style.setProperty('--image-ratio',ratio);
  const lighting=document.createElement('figure');
  lighting.className='lighting-reference';
  lighting.innerHTML=`<figcaption><span class="eyebrow">Illumination</span><span>${caption}</span></figcaption><a href="assets/${card.dataset.key}-illumination.webp" target="_blank" rel="noopener" aria-label="View ${caption.toLowerCase()}"><img src="assets/${card.dataset.key}-illumination.webp" alt="${caption}" loading="lazy"></a>`;
  card.insertBefore(lighting,card.querySelector('.card-controls'));
});
document.querySelectorAll('.comparison input[type="range"]').forEach(range=>range.addEventListener('input',()=>range.closest('.comparison').style.setProperty('--split',`${range.value}%`)));
const teaserImages={main:{rgb:'teaser-rgb.png',spectral_gt:'teaser-spectral-gt.png'},video:{rgb:'video-teaser-rgb.png',spectral_gt:'video-teaser-spectral-gt.png'}};
document.querySelectorAll('[data-teaser-group]').forEach(panel=>{const group=panel.dataset.teaserGroup;panel.querySelectorAll('[data-comparison]').forEach(button=>button.addEventListener('click',()=>{panel.querySelectorAll('[data-comparison]').forEach(other=>{const active=other===button;other.classList.toggle('selected',active);other.setAttribute('aria-pressed',active)});const value=button.dataset.comparison;const image=panel.querySelector('.compare-base');image.src=`assets/${teaserImages[group][value]}`;image.alt=`${group==='main'?'Final paper teaser':'Video teaser frame'}: ${labels[value]}`;panel.querySelector('.compare-right-label').textContent=labels[value]}))});
document.querySelectorAll('.comparison-card .segmented button').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.comparison-card');const side=button.dataset.side;card.querySelectorAll(`[data-side="${side}"]`).forEach(other=>other.setAttribute('aria-pressed',other===button));const value=button.dataset.value;const image=card.querySelector(side==='left'?'.compare-overlay':'.compare-base');image.src=`assets/${card.dataset.key}-${value}.${card.dataset.format}`;image.alt=`${card.querySelector('h3').textContent}: ${labels[value]}`;card.querySelector(side==='left'?'.compare-left-label':'.compare-right-label').textContent=labels[value]}));

const translations=new Map([
  ['RESEARCH PROJECT','研究项目'],['Overview','概览'],['Method','方法'],['Results','结果'],['Materials','材料'],['Narrowband','窄带光源'],['Renderers','渲染器'],['Paper','论文'],
  ['SPECTRAL RENDERING THROUGH RGB PIPELINES','通过 RGB 流水线实现光谱渲染'],['Spectral Rendering','光谱渲染'],['Without','无需'],['a Spectral Renderer','光谱渲染器'],['Learned','学习式'],['Spectral Codes','光谱编码'],
  ['Carry spectral information through an ordinary RGB pipeline.','让普通 RGB 流水线也能传递光谱信息。'],['Six latent channels. Two RGB passes. No renderer modification. Narrowband lights included.','六个潜在通道。两次 RGB 渲染。无需修改渲染器。支持窄带光源。'],['Explore the results','查看结果'],
  ['01 / WORK A LITTLE COLOR MAGIC','01 / 色彩魔法'],['See the difference.','观察差异。'],['Move the divider.','拖动分隔线。'],['Compare the final paper teaser and a video-teaser frame across the same three rendering routes.','在相同的三种渲染路径下比较论文主图与视频预告帧。'],['SCENE 1','场景 1'],['SCENE 2','场景 2'],["The spots on the rabbit's chest represent Monte Carlo noise rather than a persistent color deviation.",'兔子胸口的彩色光斑来自蒙特卡洛随机噪声，并非稳定的颜色偏差。'],['RGB baseline','RGB 基线'],['Spectral reference','光谱参考'],['Compared with our codec · k = 6','与我们的编码器比较 · k = 6'],['Our codec','我们的方法'],['RECONSTRUCTION','重建'],['RENDERING COST','渲染开销'],["Two unmodified RGB passes reconstruct a spectral image across the scene's glass, conductors, scattering materials and participating-medium fog.",'两次未经修改的 RGB 渲染即可重建包含玻璃、导体、散射材料和参与介质雾的光谱图像。'],["Median end-to-end wall-clock difference from Mitsuba 3 hero-wavelength sampling on the paper's Cornell-box sweep; 14 of 15 configurations lie within ±10%.",'在论文的 Cornell box 扫描实验中，相较 Mitsuba 3 主波长采样的端到端时间差中位数；15 种配置中有 14 种位于 ±10% 以内。'],['Timing is scene-dependent: the final paper reports larger gaps on scenes dominated by geometry traversal.','耗时取决于场景：论文指出，在以几何遍历为主的场景中差异会更大。'],
  ['02 / THE IDEA','02 / 核心思想'],['Keep spectral information.','保留光谱信息。'],['Keep the RGB renderer.','保留 RGB 渲染器。'],['Three RGB channels describe a colour, but not the spectrum behind it. When light interacts with glass, metals or scattering media, collapsing that spectrum too early changes the final appearance.','三个 RGB 通道可以描述颜色，却无法描述颜色背后的光谱。当光与玻璃、金属或散射介质相互作用时，过早压缩光谱会改变最终外观。'],['We encode visible-range spectra as compact latent vectors that a conventional RGB renderer can process. Two passes carry six latent channels through the existing pipeline; a linear decoder then reconstructs the spectral result.','我们将可见光谱编码为传统 RGB 渲染器能够处理的紧凑潜在向量。两次渲染在现有流水线中传递六个潜在通道，再由线性解码器重建光谱结果。'],['One codec covers reflectance, illumination, coloured glass, conductors and participating media. Lightweight upsamplers also provide a route for legacy RGB assets.','一个编码器即可覆盖反射率、照明、有色玻璃、导体和参与介质；轻量级上采样器也能让传统 RGB 素材接入同一流程。'],['channels','通道'],['Compact spectral code','紧凑光谱编码'],['passes','次渲染'],['Standard RGB rendering','标准 RGB 渲染'],['engines','个引擎'],['Cross-renderer evaluation — and more','跨渲染器评估及更多'],
  ['03 / HOW IT WORKS','03 / 工作原理'],['Change the representation.','改变表示方式。'],['Preserve the arithmetic.','保留运算结构。'],['Select a stage to follow the spectral signal through an RGB pipeline.','选择一个阶段，查看光谱信号如何通过 RGB 流水线。'],['01 / ENCODE','01 / 编码'],['Spectrum → latent code','光谱 → 潜在编码'],['N(could be 31, 61...) wavelength samples → 6 channels','N（可为 31、61……）个波长采样 → 6 个通道'],['02 / RENDER','02 / 渲染'],['Two RGB passes','两次 RGB 渲染'],['Three latent channels per pass','每次渲染三个潜在通道'],['03 / DECODE','03 / 解码'],['Recover the colors','恢复颜色'],['Linear decode → display colour','线性解码 → 显示颜色'],['Encode what light transport needs','编码光传输所需的信息'],['A non-negative linear encoder compresses each spectrum to six channels. Linearity preserves scaling and addition exactly; training makes channel-wise multiplication approximate the corresponding spectral operation.','非负线性编码器将每个光谱压缩为六个通道。线性结构精确保留缩放和加法，训练则使逐通道乘法逼近对应的光谱运算。'],['Let the RGB renderer process the code','让 RGB 渲染器处理编码'],['The six latent channels are split into two RGB triplets. Existing shading and light-transport operations process these triplets in two ordinary passes, without changes inside the renderer.','六个潜在通道被拆分为两组三通道数据，现有着色与光传输运算通过两次普通渲染处理它们，无需修改渲染器内部。'],['Recover spectral information','恢复光谱信息'],['A well-trained linear decoder merges the six rendering channels and decodes them, before converting them for colour display. Lightweight upsamplers can bring legacy RGB assets into the same latent space.','训练良好的线性解码器合并六个渲染通道并完成解码，再转换为显示颜色。轻量级上采样器可将传统 RGB 素材映射到同一潜在空间。'],['WHY k = 6?','为什么 k = 6？'],["Three channels face a trade-off between colour reconstruction and multiplication. Nine channels require another render pass with limited quality benefit in the paper's evaluation. Six channels are the practical operating point.",'三个通道需要在颜色重建和乘法精度之间取舍；九个通道需要额外一次渲染，而论文评估中的质量收益有限。因此六个通道是实用的平衡点。'],
  ['04 / MATERIAL TESTS','04 / 材料测试'],['One codec.','一个编码器。'],['Different material physics.','适应不同材料物理。'],['Each card compares the codec with a conventional RGB render or the spectral reference. Drag its divider to inspect the material response.','每张卡片将编码结果与传统 RGB 渲染或光谱参考进行比较；拖动分隔线检查材料响应。'],["Material images and masked ΔE₂₀₀₀ measurements come from the final paper's material-class evaluation. The values describe these specific scenes and sampling conditions.",'材料图像和掩膜 ΔE₂₀₀₀ 测量来自论文的材料类别评估；数值仅对应这些特定场景与采样条件。'],
  ['05 / NARROWBAND ILLUMINATION','05 / 窄带照明'],['Not only broadband.','不止宽带光源。'],['True narrowband lights.','真正的窄带光源。'],['Three Gaussian illumination cells test the codec under blue, green and red narrowband light. Each has a full width at half maximum (FWHM) of 40 nm.','三个高斯照明单元分别在蓝、绿、红窄带光源下测试编码器；每个光源的半高全宽（FWHM）均为 40 nm。'],['Within each cell, RGB, our k = 6 result and the spectral reference use one common exposure. Errors are ΔE₂₀₀₀ against the spectral reference over the 52-cell Cornell-box sweep.','每个单元中的 RGB、我们的 k = 6 结果和光谱参考均使用同一曝光。误差为 52 单元 Cornell box 扫描中相对光谱参考的 ΔE₂₀₀₀。'],['BLUE CELL · FWHM 40 NM','蓝色单元 · FWHM 40 NM'],['GREEN CELL · FWHM 40 NM','绿色单元 · FWHM 40 NM'],['RED CELL · FWHM 40 NM','红色单元 · FWHM 40 NM'],['Gaussian narrowband illumination centred at 425 nm.','中心波长为 425 nm 的高斯窄带照明。'],['Gaussian narrowband illumination centred at 525 nm.','中心波长为 525 nm 的高斯窄带照明。'],['Gaussian narrowband illumination centred at 625 nm.','中心波长为 625 nm 的高斯窄带照明。'],['ILLUMINATION SPD','照明 SPD'],['Gaussian spectrum · FWHM 40 nm','高斯光谱 · FWHM 40 nm'],['Compare with','比较对象'],['NARROWBAND','窄带'],['MATERIAL','材料'],['RENDERER','渲染器'],
  ['06 / CROSS-RENDERER EVALUATION','06 / 跨渲染器评估'],['Four renderers.','四种渲染器。'],['The same two-pass interface.','相同的两次渲染接口。'],["Compare each engine's codec render with its RGB baseline and reconstructed spectral reference. You can also select the full route that starts from RGB assets.",'比较各引擎的编码渲染、RGB 基线和重建光谱参考；也可选择从 RGB 素材开始的完整路径。'],['Where it applies','适用范围'],['Spectral effects expressible through channel-wise light-transport arithmetic, including reflectance, illumination, coloured glass, conductors, subsurface scattering and participating media.','可通过逐通道光传输运算表达的光谱效应，包括反射率、照明、有色玻璃、导体、次表面散射和参与介质。'],['Show','显示'],['Codec · spectral assets','编码器 · 光谱素材'],['Full RGB-asset route','完整 RGB 素材路径'],['Illumination','照明'],
  ['READ THE RESEARCH','阅读研究'],['Go deeper.','深入了解。'],['Read the paper.','阅读论文。'],['Research paper','研究论文'],['Final manuscript / PDF','最终稿 / PDF'],['Supplemental material','补充材料'],['Further derivations and evaluations / PDF','更多推导与评估 / PDF'],['CITE THIS WORK','引用本研究'],['BibTeX.','BibTeX。'],['Preprint and publication.','预印本与正式出版版本。'],['Use the TOG entry for the published article. The arXiv entry is included while the preprint remains available.','正式发表文章请使用 TOG 条目；预印本仍可访问期间同时保留 arXiv 条目。'],['arXiv preprint','arXiv 预印本'],['Figures and measurements from the final manuscript','图像与测量数据来自最终稿'],['Back to top ↑','返回顶部 ↑']
]);
translations.set('NARROWBAND','窄带测试');
translations.set('MATERIAL','材料类型');
translations.set('RENDERER','渲染引擎');
[
  ['Coloured glass','有色玻璃'],['OG550 · surface transmittance','OG550 · 表面透射率'],['A sharp spectral cutoff in Schott glass is difficult to preserve after an early RGB collapse.','Schott 玻璃的陡峭光谱截止特性在过早压缩为 RGB 后很难保留。'],
  ['Gold conductor','金导体'],['Measured metal · D65','实测金属 · D65'],['The spectral Fresnel response preserves the hue and intensity of metallic reflection.','光谱菲涅耳响应保留了金属反射的色相和强度。'],
  ['Subsurface scattering','次表面散射'],['Wine · homogeneous medium','葡萄酒 · 均匀介质'],['Absorption and scattering travel through the renderer as encoded per-channel volume parameters.','吸收与散射以编码后的逐通道体积参数通过渲染器传递。'],
  ['Heterogeneous volume','非均匀体积'],['Per-voxel spectral hand','逐体素光谱手部'],['Spatially varying skin features, including freckles, knuckles and veins, remain distinguishable.','雀斑、指关节和静脉等空间变化的皮肤特征仍然清晰可辨。'],
  ['Mean ΔE₂₀₀₀: 1.28 codec / 10.52 RGB','平均 ΔE₂₀₀₀：编码器 1.28 / RGB 10.52'],['Mean ΔE₂₀₀₀: 0.65 codec / 8.98 RGB','平均 ΔE₂₀₀₀：编码器 0.65 / RGB 8.98'],['Mean ΔE₂₀₀₀: 2.19 codec / 14.39 RGB','平均 ΔE₂₀₀₀：编码器 2.19 / RGB 14.39'],['Mean ΔE₂₀₀₀: 0.93 codec / 4.00 RGB','平均 ΔE₂₀₀₀：编码器 0.93 / RGB 4.00'],
  ['Mean / p95 ΔE₂₀₀₀ — ours: 1.50 / 3.37 · RGB: 23.78 / 52.31','平均值 / p95 ΔE₂₀₀₀ — 我们：1.50 / 3.37 · RGB：23.78 / 52.31'],['Mean / p95 ΔE₂₀₀₀ — ours: 1.17 / 3.04 · RGB: 12.48 / 35.48','平均值 / p95 ΔE₂₀₀₀ — 我们：1.17 / 3.04 · RGB：12.48 / 35.48'],['Mean / p95 ΔE₂₀₀₀ — ours: 1.08 / 2.42 · RGB: 21.68 / 44.24','平均值 / p95 ΔE₂₀₀₀ — 我们：1.08 / 2.42 · RGB：21.68 / 44.24'],
  ['Broadband coloured lights','宽带彩色光源'],['Open-source path tracing under broadband illumination.','宽带照明下的开源路径追踪。'],['Environment-map lighting','环境贴图照明'],['Product visualisation under a spectral environment map.','光谱环境贴图下的产品可视化。'],['Structured light · light 2','结构化光源 · light 2'],['Offline production rendering with spectrally structured illumination.','使用光谱结构化照明的离线制作级渲染。'],['Lumen · lighting 1','Lumen · lighting 1'],['A real-time pipeline with Lumen global illumination.','采用 Lumen 全局光照的实时流水线。'],
  ['Broadband light spectra','宽带光源光谱'],['Structured light spectrum','结构化光源光谱'],['Environment illumination','环境照明'],['Scene light spectra','场景光源光谱'],
  ['The final paper constructs a 16-pass spectral reference inside each production pipeline using uplifted material spectra and known light spectra. “Codec” applies the six-channel codec to those spectral assets; “Full RGB-asset route” adds the paper\'s RGB upsamplers. It is a constructed reference, not a native spectral mode of these engines. The selected Maya scene uses structured lighting; the paper also reports a nearly flat broadband case where RGB is most accurate.','论文在每个制作流水线中使用上采样材料光谱和已知光源光谱构建 16 次渲染的光谱参考。“编码器”将六通道编码应用于这些光谱素材；“完整 RGB 素材路径”进一步加入论文的 RGB 上采样器。这是构建的参考结果，并非这些引擎的原生光谱模式。所选 Maya 场景采用结构化照明；论文也报告了近乎平坦的宽带光源案例，此时 RGB 最准确。']
].forEach(([en,zh])=>translations.set(en,zh));
const reverseTranslations=new Map([...translations].map(([en,zh])=>[zh,en]));
let currentLanguage='en';
const languageSwitch=document.querySelector('#language-switch');
function translateTextNode(node,language){const raw=node.nodeValue;const trimmed=raw.trim();if(!trimmed)return;const translated=(language==='zh'?translations:reverseTranslations).get(trimmed);if(translated&&translated!==trimmed)node.nodeValue=raw.replace(trimmed,translated)}
function translateTree(root,language){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{if(!node.parentElement?.closest('script,style,pre,code'))translateTextNode(node,language)})}
function applyLanguage(language){currentLanguage=language;translateTree(document.body,language);document.documentElement.lang=language==='zh'?'zh-CN':'en';languageSwitch.textContent=language==='zh'?'EN':'中文';languageSwitch.setAttribute('aria-label',language==='zh'?'Switch to English':'切换为中文');languageSwitch.setAttribute('aria-pressed',language==='zh');try{localStorage.setItem('spectral-language',language)}catch{}}
languageSwitch.addEventListener('click',()=>applyLanguage(currentLanguage==='en'?'zh':'en'));
const languageObserver=new MutationObserver(records=>{if(currentLanguage!=='zh')return;records.forEach(record=>{record.addedNodes.forEach(node=>{if(node.nodeType===Node.TEXT_NODE)translateTextNode(node,'zh');else if(node.nodeType===Node.ELEMENT_NODE)translateTree(node,'zh')});if(record.type==='characterData')translateTextNode(record.target,'zh')})});
languageObserver.observe(document.body,{subtree:true,childList:true,characterData:true});
let savedLanguage='en';try{savedLanguage=localStorage.getItem('spectral-language')==='zh'?'zh':'en'}catch{}applyLanguage(savedLanguage);
